### ISSUE TITLE
TotalTerminal keeps it's height on screen resize

### ISSUE THREAD

**Issue by A2K** [binaryage/totalterminal#14] opened 2011-08-04 18:48 UTC
Steps:
1. Set screen resolution to 1280x800 and start up TotalTerminal
2. Change screen resolution to 1920x1200 and open TotalTerminal again by hotkey

Result:
TotalTerminal window height is the same as it was n 1280x800 screen resolution

Expected result:
TotalTerminal window height should keep proportions after changing screen size.

For example, I plug in a fullhd monitor into my 13" macbook pro. When I start TotalTerminal on my laptop without monitor plugged in and them close the laptop and plug in monitor, the TotalTerminal window height keeps the same as it was on 1280x800. But I would like it to be maximized on any screen size.

It worked as expected on Visor, but was broken in first versions of TotalTerminal.

**Comment by parabolala** [comment] 2011-08-04 19:29
Same for me

**Comment by denplis** [comment] 2011-08-04 19:29
I have the same problem, it is very annoying, please fix this bug.

**Comment by A2K** [comment] 2011-08-08 14:11
This was fixed in 1.1.1, thank you very much!

**Comment by darwin** [comment] 2011-08-08 14:32
Really? I don't think this was fixed. The height of Terminal window is kept by Terminal.app itself and can be changed in `Preferences -> Settings -> Window -> Rows`. As far as I know this rows number does not change when you change resolution. So the height should not proportionally change as a result.

**Comment by A2K** [comment] 2011-08-08 14:47
It works correctly for me now, just like it worked with Visor.
When I start TotalTerminal on my 13" macbook (1280x800), it starts attached to menu panel on top of the screen and stretched down almost to bottom of the screen. On 1.1 when I plugged 24" (1920x1080) monitor into my laptop, the windows kept it's height, but stretched horizontally to full screen width. On 1.1.1 windows stretches vertically too, so it fill almost all screen height on any resolution.
Same works correctly when I start TotalTerminal on 24" screen and then switch to 13".

So it looks like it changes row count correctly too, but I'm not sure about all cases, maybe it works correctly only for my setup.

**Comment by A2K** [comment] 2011-08-08 14:52
There is this line in 1.1.1 changelog:
"Visor Window width adapts to screen resolution changes (the bug was introduced in TotalTerminal 1.0)"
looks like height now adapts too.

**Comment by darwin** [comment] 2011-08-08 14:53
I can confirm this fix of width update when display configuration changes. But the original issue was about proportional height when display height changes.

I've just tested it and it keeps rows and height the same.

**Comment by A2K** [comment] 2011-08-08 14:59
Yes, you are right. That was my mistake – actually I was thinking about stretching to full screen height, which is a special case of keeping proportions. I'm not sure that application really needs to keep proportions in all cases – that's for you to decide.

**Comment by darwin** [comment] 2011-08-08 15:03
Personally I don't need this feature and I think it would benefit just a few people. Ok, let's close it :-)

**Closed as completed by darwin** 2011-08-08 15:03 UTC

**Comment by JacopKane** [comment] 2012-07-30 19:41
It's randomly happening to me often since i started to using it for long time on at least two different machines. Opening a pinned opposite TotalTerminal window from bottom (It's pushing terminal to top when it was opened and hopefully it fixes terminal height issue after few tries) can fix issue sometimes.
