### ISSUE TITLE
Active on all Spaces should work with Fullscreen Apps

### ISSUE THREAD

**Issue by cpojer** [binaryage/totalterminal#12] opened 2011-08-04 06:03 UTC
This is a feature request and I'm not sure if this is easily or at all possible - so feel free to close it.

It would be nice if TotalTerminal would work on Spaces with Fullscreen Apps. I use my Text-Editor in full-screen mode and I miss this functionality.

What currently happens on Lion is that when you are in a fullscreen App and you open the visor using a keyboard shortcut it takes you to the previously active Space and shows visor. When you close the visor it goes back to the Full screen app.

If this is possible it would also be great to have this in TotalFinder.

**Comment by darwin** [comment] 2011-08-07 20:23
dupe of #5, closing

**Closed as completed by darwin** 2011-08-07 20:23 UTC
